### ISSUE TITLE
table annotation color column inconsistent

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie.github.io#100]
Hi,

I fell into the following trap:

- the `lut` view entry for segmentation expects `"argbColumn"`
- however, the format of the values in this column is RGBA

Can we make this consistent?
I suggest changing the `lut` to `"rgbaColumn"`

**Comment by tischi** [comment]
Ah, good point.

@constantinpape in order to avoid changing all projects now, maybe we could support both 

`argbColumn  @Deprecated`
`rgbaColumn`

**Comment by constantinpape** [comment]
I went ahead and added `rgbaColumn` to the schema: https://github.com/mobie/mobie.github.io/commit/852cd6a75ddc0124abe469fbb92e08067e2bf812

That's all the changes needed in the schema for this (there isn't a conept for deprecation); so you can go ahead and adapt this in mobie-fiji as well.
