### ISSUE TITLE
Spec: menuItem

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#11]
```        
        ....
        "menuItem": "image/name",
        "view": {
          "sourceDisplays": [
            {
              "imageDisplays": {
                "color": "green",
                "contrastLimits": [
                  0.0,
                  255.0
```

I feel now that the `menuItem` should be a property of the `view`, because the user can only select views in the menu. 

I think also for the other (bookmark/multi-source) views, we need a `menuItem`.

**Comment by constantinpape** [comment]
Ok, we can do this. Then `view` should look like this:

```json
`view`: {
  `menuItem`: "",
  "sourceDisplays": {},
  "..."
}
```

> I think also for the other (bookmark/multi-source) views, we need a `menuItem`.

Yes, we don't really distinguish between "normal" and "bookmark" views in the view itself anyway.
One point I am not so sure about is the hierarchy of menu items here thoguh:

In a `view` that is given for a source `"menuItem": "image/name"` is well defined and will result in the menu "image" with entry "name".
But how does this work for bookmark views? Right now we always put them into the "bookmark" menu without further nesting
(and I think it should stay like this). So maybe we say that bookmark views should have `"menuItem": "bookmark/name"` and if something else than "bookmark" is given we just ignore that?

**Comment by tischi** [comment]
>  So maybe we say that bookmark views should have "menuItem": "bookmark/name" and if something else than "bookmark" is given we just ignore that?

I would get back to this once I am implementing this part; for now I would suggest just put something there.

**Comment by constantinpape** [comment]
Done in  4ecb062. Leaving this issue open to discuss details of the menuItem format later.

**Comment by constantinpape** [comment]
We have `uiSelectionGroup` now, that specifies the menu name. The name in the menu is always the source name.
