### ISSUE TITLE
Default Viewertransform

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#13]
If there is a view shown with multiple sources and no viewer transform is given.
What should be the viewer transform?

1. Zoom in on one of the sources?
2. Try to find a view where one can see all the sources?

**Comment by constantinpape** [comment]
I think 2 would be better if that's feasible.

**Comment by tischi** [comment]
Ok, I will do this: https://github.com/bigdataviewer/bigdataviewer-playground/issues/67

**Comment by constantinpape** [comment]
This is working.
