### ISSUE TITLE
Current example

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#14]
@constantinpape 
In the current example that you provide on /g/kreshuk/pape/Work/data/mobie/example-project/example-dataset/, could you please also add a segmentation to  `"views": {  "default": {...`?

**Comment by constantinpape** [comment]
Sure. Should I also update the spec accoridng to our recent discussions?

**Comment by tischi** [comment]
This would be great, also if you could do it kind of now ;-)
Because then I can continue developing (managed to have the whole day for this).

**Comment by constantinpape** [comment]
I am on it.

**Comment by constantinpape** [comment]
@tischi I have updated the example project and the default view now also has the segmentation.
