### ISSUE TITLE
Additive vs exclusive views

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#21]
I realized that we need two different kind of views:
- additive: the view gets added on top of the current viewer state (e.g. for the source default views or views that only have a viewer transform)
- exclusive: the view replaces the current viewer state (most of our old bookmarks that have  `layers`)

I think we need to be explicit about this and add a boolean field to `view` to represent this.
Maybe `isExclusive` or `isAdditive`?

What do you think, @tischi, @K-Meech?

**Comment by tischi** [comment]
Good one. Let's add `isExclusive`.

**Comment by constantinpape** [comment]
Done.
