### ISSUE TITLE
Sources without a default view

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#22]
There could be sources for which we don't want to add a default view, because it doesn't make much sense (or overloads the menus) to select them individually. A prime example are images in a HCS plate.
To support this the `view` field in `source` should not be required.

To add these sources, one would then add a view to `views`, e.g.for a HCS plate:
```json
{
  "sources": {"dapi-A1": {}, "dapi-A2": {}, "dapi-A3": {}, "dapi-A4": {}},
  "views": {"dapi": {"imageDisplay": "select all dapi images"}, "sourceTransforms": {"autogrid for all dapi images"} }} 
}
```
This view should be additive, see #21.

What do you think, @tischi?

**Comment by constantinpape** [comment]
I removed view from the required fields for a source for now.

**Comment by tischi** [comment]
> I removed view from the required fields for a source for now.

I think that makes a lot of sense!
