### ISSUE TITLE
Alpha 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#33]
`alpha` (or better `opacity`?!) should also be a field of `imageDisplay`.

In java I have `sourceDisplay` as the base class and `segmentationDisplay` and `imageDisplay` extend this, are we also describing the fields like this in the spec?

**Comment by constantinpape** [comment]
Ok, I will add it to `imageDisplays`. And I agree, `opacity` is a better name, I will change it.

**Comment by constantinpape** [comment]
Done.
