### ISSUE TITLE
Remote vs. local

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#36]
Right now my code looks like this, only allowing for two image data locations (S3 and FS):

```
		if ( options.values.getImageDataStorageModality().equals( MoBIEOptions.ImageDataStorageModality.S3 ) ) 
			imageDataLocation = "remote";
		else
			imageDataLocation = "local";
```

Not sure what to do here...

**Comment by tischi** [comment]
If we keep this logic, maybe we could rename remote to S3 and local to FS?

**Comment by constantinpape** [comment]
> If we keep this logic, maybe we could rename remote to S3 and local to FS?

Yes, that's a good point. Also if we potentially want to support other object stores like GCS or ABS at some point.

**Comment by tischi** [comment]
ok, should we change spec? maybe something a bit more readable: `s3object`, `file`?

**Comment by constantinpape** [comment]
> ok, should we change spec? maybe something a bit more readable: `s3object`, `file`?

Yes, let's do it. I will change it this afternoon.

**Comment by constantinpape** [comment]
Do you mind if we call it `s3store` instead? `s3object` sounds like we are referring to a specific object in the object store.

**Comment by tischi** [comment]
s3store and fileSystem?

**Comment by constantinpape** [comment]
Update in the schema, the two projects on git that have branches with the new spec and in the example project.
