### ISSUE TITLE
numTimepoint

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#37]
It is annoying, but when instantiating BDV one must say how many time points there will maximally be in the dataset.
I would thus propose adding this information to the dataset.json:

```
{
  "is2d": false,
   "timepoints": 20,
    ...
}
```

OK? Could you do this for the arapidopsis?

**Comment by constantinpape** [comment]
Yes, I will add it for Arabidopsis.
In general, I think it should be optional in the spec and default to 1, do you agree?

**Comment by constantinpape** [comment]
I have added it for the arabidopsis dataset.
