### ISSUE TITLE
Acknowledge Sian

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#4]
We totally must not forget to properly acknowledge @superresolusian for the genius suggestion of the name MoBIE 😄  Thank you so much already @superresolusian! For sure we will tweet accordingly when we release the happy wale to the public.

cc @constantinpape

**Comment by constantinpape** [comment]
We'll add Sian and Gemma to the Acknowledgments in the publication; I think we can then also create a "Publication" section on the website and repeat the most important Acknowledgements there.

**Comment by constantinpape** [comment]
Acknowledgments are all in the paper / preprint.
