### ISSUE TITLE
3D viewer

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#40]
@constantinpape 

In principle we can also show whole images in 3D; should we further support this?
Then we would need a spec: `showImageIn3D` or something.
I would lean towards not supporting image display in 3D initially...

**Comment by constantinpape** [comment]
we have it in the spec already:
see `showImagesIn3d` here: https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json

**Comment by tischi** [comment]
ok!
