### ISSUE TITLE
RGBA color strings

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#41]
@tischi @K-Meech 
In the current bookmarks in platybrowser the rbga colors were saved like this: `(r=255,g=255,b=255,a=255)`.
The regex I have in the jsonschema doesn't accept this because of the parentheses, i.e. only `r=255,g=255,b=255,a=255` is valid.
I would suggest to use the version without parentheses, because they don't add any information here.

Any objections?

**Comment by tischi** [comment]
No objections

**Comment by K-Meech** [comment]
No objections - sounds good!
