### ISSUE TITLE
Viewing individual sources when there also is a grid view

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#42]
@constantinpape 

Viewing these two sources together makes no sense, but is possible.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/2157566/115388047-b87c5d80-a1db-11eb-96a6-245a57825c59.png">

Should we add `sourceTransformations` to the individual views of the images such that they appear at the same position as they would in the `gridView`? 

Or, maybe completely not show the individual sources in the UI?

Or something else?

**Comment by constantinpape** [comment]
> Viewing these two sources together makes no sense, but is possible.

I am not so sure. There might be some use case for this. E.g. one has many specimen used to build an atlas and then wants to compare some of the specimen before / after registration to the atlas.

**Comment by tischi** [comment]
That is true...

Even this specific case showing a segmentation of another image on top of raw data that is was not derived from may make sense, because one may want to check whether some sort of reference segmentation would look good on some particular newly acquired raw data. 

I'll close for now.
