### ISSUE TITLE
Is it possible to have inverted contrast using min/max intensities?

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie.github.io#45]
Hi,

a user asks for inverted contrast. Could I just specify the values accordingly with `max < min`?

**Comment by tischi** [comment]
I _think_ that works. 

Could you please try whether this is currently possible in
1. The BDV B&C UI
2. The MoBIE B&C UI

**Comment by martinschorb** [comment]
- MoBIE1 UI: does not work (source gets all black)
- BDV UI: does not work (other value gets forced to `min=max`)

I have not tested what happens when providing `max<min` in the attributes.

**Comment by tischi** [comment]
Should I try to enable it in the MoBIE UI?
Because if we provide it in the attributes it should play well with the UI.

**Comment by martinschorb** [comment]
> Should I try to enable it in the MoBIE UI?

I fully support that

**Comment by martinschorb** [comment]
- BDVPG: boom https://github.com/bigdataviewer/bigdataviewer-playground/issues/223

**Comment by constantinpape** [comment]
Also related to https://github.com/mobie/mobie-viewer-fiji/issues/169

**Comment by tischi** [comment]
Seems to work:

<img width="415" alt="image" src="https://github.com/mobie/mobie.github.io/assets/2157566/c02f5e58-b48a-41b5-9601-1fb2c00bf640">
<img width="417" alt="image" src="https://github.com/mobie/mobie.github.io/assets/2157566/62626de2-429c-4f3d-99cd-273f769916e8">

Closing this.
