### ISSUE TITLE
Remove view from source

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#46]
@constantinpape @martinschorb 

The discussion about the crop indicated to me that it is confusing to have a "default" view within the source in `sources`. Would you mind _not_ supporting this anymore and move those views into `views`.

Several reasons:

1. Within views one can specify a name that is different to the source name
2. Maybe sometimes people do not want to have a "default" view on a specific source, but, e.g. only a collection of crops
3. Conceptually it feels cleaner to fully separate the `sources` from the `views`
4. It would simplify both our spec as well as my code because I don't have to look for the views in two places

**Comment by constantinpape** [comment]
Yes, I think this makes a lot of sense. I will change it in the spec and the python code and update our example projects.

**Comment by tischi** [comment]
Thanks! I think this is a conceptually very nice improvement!

**Comment by constantinpape** [comment]
I changed it in the spec and the python utils.
I also made this branch for you to test it:
https://github.com/mobie/zebrafish-lm-datasets/pull/3

Let me know when this works in MoBIE, I will merge it into the `spec-v2` branch then and update the other datasets.

**Comment by tischi** [comment]
Works! Thanks!

**Comment by constantinpape** [comment]
> Works! Thanks!

Ok, should I update the other projects?

**Comment by tischi** [comment]
Yes, please!
Also the crop test project on your server please.

**Comment by constantinpape** [comment]
Ok, I updated it now for all the projects that have a spec-v2 branch:
- https://github.com/mobie/platybrowser-datasets/tree/spec-v2
- https://github.com/mobie/yeast-clem-datasets/tree/spec-v2
- https://github.com/mobie/arabidopsis-root-lm-datasets/tree/spec-v2
- https://github.com/mobie/zebrafish-lm-datasets/tree/spec-v2

and for the crop test project.

I think everything is done here, so I am closing the issue. Feel free to reopen if anything still needs to be changed here.
