### ISSUE TITLE
Link to new spec

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#48]
@constantinpape 

I added this: https://github.com/mobie/mobie.github.io#visit-the-rendered-pages
Is it possible to also add a link there now already to the new spec?

**Comment by constantinpape** [comment]
The spec is already there:
https://mobie.github.io/specs/mobie_spec.html
And you can see it on the mobie.github.io front page if you scroll to the bottom.

**Comment by tischi** [comment]
I see, but that's the new one, not supported by MoBIE in Fiji yet, right?
Maybe we should say this?

**Comment by constantinpape** [comment]
> I see, but that's the new one, not supported by MoBIE in Fiji yet, right?

Yes, it's the new one. There is not a real description of the current spec.

> Maybe we should say this?

Yes, I added one sentence. But I hope we can switch everything to the new spec soon.
(From my side this is mostly done and we would only need to merge the `spec_v2` branches into master. Only updating the covid tomo project might still be a bit work if we want to switch it to the new grid view.)
