### ISSUE TITLE
Towards support for ome.zarr

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#52]
Add "prototype" support for ome.zarr fle format:

- [x] Implement new file format spec, see #49
- [x] Add ome.zarr to the spec
- [x] Create an example project based on ome.zarr v0.3 (with bdv xml)
- [x] Enable opening this with MoBIE Fiji
- [x] Create an example project without bdv xml
- [x] Enable opening this in MoBIE
- [x] (Enable writing ome.zarr with MoBIE project creator)

I will work on the first 3 points, @KateMoreva will work on implementing the reader in MoBIE (once I have created the example project!).
The last point would probably be done by @K-Meech, but I am not sure if we need to work on this already, I just added it here for completeness.

cc @joshmoore: this will also serve as example data and reader for v0.3.

**Comment by constantinpape** [comment]
I started to work on this:
- Functionality to write [ngff data](https://github.com/constantinpape/elf/blob/master/elf/io/ngff.py)
- Script to create ngff example data for [covid-em data](https://github.com/mobie/covid-em-datasets/blob/master/ngff-example/create_ngff_example.py)

**Comment by constantinpape** [comment]
I have created an example project with "bdv.ome.zarr" and "bdv.ome.zarr.s3" formats. This means the data is in ome.zarr format, but we are still using a bdv xml file in MoBIE, because we can't save the voxel size in ome.zarr yet (for v0.3).
The example project is available:
- [per download](https://oc.embl.de/index.php/s/KLTaSgX1c4zgnHP).
- on the EMBL share: `/g/kreshuk/pape/Work/mobie/covid-em-datasets/ngff-example/data`
- on s3: https://s3.embl.de/i2k-2020/project-bdv-ome-zarr

The available image data (ome.zarr and xml files) can be found in the folder `Covid19-S4-Area2/images/bdv.ome.zarr`.
So we can already start with adapting the readers in MoBIE:

## From filesystem

Goal: the [fiji command to open ome.zarr from the filesystem](https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/ui/OpenOMEZARRCommand.java) should work with the `raw.ome.zarr` file.

What needs to be adapted for the ome.zarr v3 format (list of necessary changes may not be exhaustive):
- The `transform` field does not exist, but the current code should still work, because it uses `try-excepts`, e.g [here](https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/N5OMEZarrImageLoader.java#L328-L336) and [here](https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/N5OMEZarrImageLoader.java#L379-L386).
- The data can now have variable dimensions from 2d to 5d. We should check that we can read the data, by ensuring that the `axes` field contains 
`["z", "y", "x"]`, i.e. is 3 dimensional. And we need to get rid of other 5d changes, e.g. [here](https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/N5OMEZarrImageLoader.java#L578-L579).

## From s3

Goal: the [fiji command to open ome.zarr from s3](https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/ui/OpenOMEZARRFromS3Command.java) should work for loading the `raw.ome.zarr` file from s3.

This should not require any additional changes once the filesystem version works.

## Next steps

Once https://github.com/mobie/mobie-viewer-fiji/pull/293 is merged, we can add the `bdv.ome.zarr` and `bdv.ome.zarr.s3` file formats and integrate the loaders with the mobie spec, so that the example project can be loaded in MoBIE (both from the filesystem and from s3).

**Comment by constantinpape** [comment]
The PR https://github.com/mobie/mobie-viewer-fiji/pull/297 is progressing and I think we should have a first version that can read the example data tomorrow or early next week. 

Once that works and is cleaned up a bit we should make a larger clean up and extension of the (ome) zarr readers:
- [ ] Add [n5-zarr](https://github.com/saalfeldlab/n5-zarr) as dependency and remove the code that was copied from there, e.g. the [N5ZarrReader](https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/de/embl/cba/mobie/n5/zarr/N5ZarrReader.java)
- [ ] Read `dimensionSeparator` from the zarr .attrs instead of hard-coding it. (Using "." as default if it's not there.)
- [ ] Generate additional example data for: `axes=["y", "x"], ["c", "y", "x"], ["c", "y", "x"], ["t", "c", "y", "x"], ["t", "c", "z", "y", "x"]` and for `dimensionSeparator="."`. (I will do this.)
- [ ] Extend the ome-zarr functionality so that all the examples can be read properly.

**Comment by constantinpape** [comment]
I have generated ngff example data for all the different axes combinations now.
It's available on:
- embl share: `/g/kreshuk/data/ngff/v.03`
- s3: `https://s3.embl.de/i2k-2020/ngff-example-data/v0.3`

**Comment by constantinpape** [comment]
@tischi, I just discussed how to continue here with @KateMoreva:
- Opening "bdv.ome.zarr" projects is now working and the PR is merged. Can you confirm that opening the example project https://s3.embl.de/i2k-2020/project-bdv-ome-zarr is working for you now?
- The next step will be to implement opening "ome.zarr" projects, using the [covid-if project](https://github.com/mobie/covid-if-project) as example.
    - Re the discussions in https://github.com/mobie/mobie-viewer-fiji/pull/347: this is clear for now, this should mostly be implemented in the "bigdataviewer-ome-zarr" repository.
- Eventually we should discuss the refactoring of N5/Zarr reader code more; I think we would want to refactor (almost?) all files in https://github.com/mobie/mobie-viewer-fiji/tree/master/src/main/java/de/embl/cba/mobie/n5 to "bigdataviewer-ome-zarr" and "bigdataviewer-n5". But before @KateMoreva is starting to work on this we should have another zoom to discuss the details.

**Comment by tischi** [comment]
I can open the project with the current master, using this:
```
 new MoBIE("https://s3.embl.de/i2k-2020/project-bdv-ome-zarr", MoBIESettings.settings().imageDataFormat(ImageDataFormat.OmeZarr));
```
Is there a reason why this is not called `ImageDataFormat.BdvOmeZarrN5`?

**Comment by constantinpape** [comment]
> Is there a reason why this is not called `ImageDataFormat.BdvOmeZarrN5`?

I think it should be called `ImageDataFormat.BdvOmeZarr`.
The fact that we use n5 for opening is an implementation detail, that should not be part of the format name.

**Comment by tischi** [comment]
Sorry, I meant: `ImageDataFormat.BdvOmeZarrS3`

**Comment by KateMoreva** [comment]
> I can open the project with the current master, using this:
> 
> ```
>  new MoBIE("https://s3.embl.de/i2k-2020/project-bdv-ome-zarr", MoBIESettings.settings().imageDataFormat(ImageDataFormat.OmeZarr));
> ```
> 
> Is there a reason why this is not called `ImageDataFormat.BdvOmeZarrN5`?

Yes, it should be named BdvOmeZarr once MoBIE could open ome.zarr files (not bdv.ome.zarr). I can push renamed files and some more changes right now if you wish (but so far MoBIE can open only BbvOmeZarr, thus the name was just OmeZarr)

**Comment by constantinpape** [comment]
Quick summary from a meeting with @KateMoreva and @tischi:
the progress on this is great and we can read all current flavors of ome.zarr now (except for from ome.zarr.s3, but only because this is missing an example project, which I will provide). The next step will be to continue refactoring this functionality into the two separate "bigdataviewer-n5" and "bigdataviewer-ome-zarr" repositories:
![Whiteboard 1 -01](https://user-images.githubusercontent.com/4263537/126300164-25005535-7285-441e-bedb-53920f8ee120.png)

The next steps for this are (not necessarily in this order):
- refactor most of the functionality in https://github.com/mobie/mobie-viewer-fiji/tree/master/src/main/java/de/embl/cba/mobie/n5 into the new repositories (except for openOrganelle, which is still experimental and the Fiji commands, which we will keep inside of MoBIE for now and could refactor into some other repository with more lightweight dependencies if needed later)
- create maven packages for the two new repos and host them via the imagej maven repository, @tischi will contact Jan Eglinger about this.
- add examples and tests (for proper CI) to the two repositories

**Comment by constantinpape** [comment]
@KateMoreva I have created the example project for ome.zarr.s3 now:
`https://s3.embl.de/i2k-2020/project-ome-zarr`.
