### ISSUE TITLE
Dataset spec

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#6]
@constantinpape 

```
cat /g/kreshuk/pape/Work/data/mobie/example-project/example-dataset/dataset.json 
{
  "dataset": {
    "is2d": false
  },
...
```

Could we rename "dataset" to "metadata"? Reason: the whole thing is a already describing the dataset. Or we remove this layer completely:

```
{
   "is2d": false
   "sources": {...}
   "views": {...}
}
```

**Comment by tischi** [comment]
removing the "dataset" completely might be better.

**Comment by constantinpape** [comment]
Sure, that works too. We should do the same in the project metadata then.

**Comment by tischi** [comment]
Ok, let's do this!

**Comment by constantinpape** [comment]
Done in  4ecb062
