### ISSUE TITLE
Remove logging?!

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#64]
@KateMoreva could we remove this logging?
`System.out.println( "No channel specified" );`
you have it in two places right now...

**Comment by KateMoreva** [comment]
@tischi 
In `mobie-io` System.out.println log is completely deleted (`develop` branch). 
Logging with **Slf4j** is used instead.
The current level is _info_, but all info logging (except for the tests) is surrounded with a check of **logChunkLoading**, thus would not be printed unless it is set to true.

**Comment by KateMoreva** [comment]
if you like this solution, please approve the [PR]( https://github.com/mobie/mobie-io/pull/39) :)

**Comment by tischi** [comment]
sounds good!
