### ISSUE TITLE
Affine transform spec

### ISSUE THREAD

**Issue by tischi** [mobie/mobie.github.io#7]
```
"sourceTransforms": [
            {
              "affine": {
                "name": "affine-0",
                "parameters": [
```

Do we need a "name" here? I don't think so...

**Comment by constantinpape** [comment]
No, we don't really need it here; I just put it in to be consistent with the `autoGrid`. But if you prefer we can get rid of it here.

**Comment by tischi** [comment]
Maybe we can also get rid of the name in `autoGrid`?! I don't think I need it on the Java side.

I started implementing and I feel the only things that really needs a name is a source and a view.

**Comment by constantinpape** [comment]
The reason to put it there for `autoGrid` was for generating a name in the bookmarks menu.
But I agree that moving menuItem to view is a better solution, so we can get rid of the name here too.

**Comment by constantinpape** [comment]
Ok, I removed all the `name` fields now.
We now only have names for source and views and they correspond to the keys in the `sources` and `views` in `dataset.json`.

**Comment by constantinpape** [comment]
I think I was a bit overzealous removing name from `imageDisplay` and `segmentationDisplay`; I think these still need a name to be displayed in the GUI to change the display settings.
What do you think @tischi, should we add the `name` again or do you want another solution for this?

**Comment by tischi** [comment]
Yes, they need a name! They are views!

**Comment by constantinpape** [comment]
I think technically they are part of a view. But I agree, they need names, I will add it again.

**Comment by constantinpape** [comment]
I re-added the names now.
