### ISSUE TITLE
Update label rendering options

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie.github.io#75]
Update the label rendering options in the documentation to match changes made for https://github.com/mobie/mobie-viewer-fiji/issues/721

**Comment by constantinpape** [comment]
Also needs to be updated here: https://mobie.github.io/tutorials/explore_a_project.html

**Comment by constantinpape** [comment]
And could you also add an example for boundary rendering in https://mobie.github.io/tutorials/exploring_segmentations.html?

**Comment by constantinpape** [comment]
Also needs to be updated in https://mobie.github.io/tutorials/views_and_locations.html

**Comment by K-Meech** [comment]
Will do!
